import {Flags} from '@oclif/core'
import {FireblocksBaseCommand} from '../../lib/base-command.js'

export default class UpdateVasp extends FireblocksBaseCommand {
  static summary = 'Add jsonDidKey to VASP details'

  static description = 'Update VASP Details.\n\nUpdates a VASP with the provided parameters. Use this endpoint to add your public jsonDIDkey generated by Notabene.\n\nOperation ID: updateVasp\nDocs: https://docs.fireblocks.com/api/swagger-ui/#/Travel%20Rule/updateVasp'

  static enableJsonFlag = false

  static flags = {
    data: Flags.string({
      description: 'JSON request body',
      required: true,
    }),
  }

  static method = 'PUT'
  static path = '/v1/screening/travel_rule/vasp/update'
  static isBeta = false

  async run(): Promise<unknown> {
    const {flags} = await this.parse(UpdateVasp)

    let body: Record<string, unknown> | undefined
    if (flags.data) {
      try {
        const parsed = JSON.parse(flags.data)
        if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) {
          this.error('--data must be a JSON object (e.g., \'{"key": "value"}\')')
        }
        body = parsed as Record<string, unknown>
      } catch {
        this.error('Invalid JSON in --data flag. Ensure the value is valid JSON.')
      }
    }

    const headers: Record<string, string> = {}
    if (flags['idempotency-key']) {
      headers['Idempotency-Key'] = flags['idempotency-key']
    }



    await this.confirmOrAbort('PUT', '/v1/screening/travel_rule/vasp/update')

    const result = await this.makeRequest(
      'PUT',
      '/v1/screening/travel_rule/vasp/update',
      {
        body,
        headers,
      },
    )

    return result
  }
}
